version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: test  # Adiciona a variável de ambiente para testes
      DATABASE_NAME: biopark_companies
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    command: >
      bash -c "until nc -z db 5432; do sleep 1; done && ./bin/rails db:create db:migrate && ./bin/rails server -b 0.0.0.0"

  
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: biopark_companies

volumes:
  postgres_data:
